### ISSUE TITLE
Battery Drain is insane on Marshmallow

### ISSUE THREAD

**Issue by xantbos** [qklabs/qksms#249] opened 2015-10-29 07:22 UTC
Just installed marshmallow last night, fresh charge going to work. Not even an hour later I have a battery warning at 15%.

I wish I had taken a screenshot, but it slipped my mind. QKSMS had used 137% battery over the last 24 hours at that point. 98% active rate in RAM.

Perhaps a 6.0 bug with perms or something? Just insane. My phone was practically on fire by the time I noticed.

**Comment by astrohm** [comment] 2015-10-29 21:42
This isn't just Marshmallow -- I'm experiencing it on 5.1 as well.

**Comment by licaon-kter** [comment] 2015-10-29 22:40
Duplicate of https://github.com/qklabs/qksms/issues/198 ?

**Comment by moezbhatti** [comment] 2015-10-30 03:23
Duplicate

**Closed by moezbhatti** 2015-10-30 03:23 UTC
