### ISSUE TITLE
show timestamps for all messages

### ISSUE THREAD

**Issue by kolAflash** [qklabs/qksms#468] opened 2016-04-07 15:41 UTC
A lot of messages don't show timestamps. It's quite randomly. Some just show a timestamp and some don't.

I can always get the timestamp via long-press -> details.
But I'd prefer to see the timestamp for every message directly.

**Comment by sm4rk0** [comment] 2016-04-07 18:06
Duplicate of #358

**Closed** 2016-04-07 20:43 UTC
Labels: duplicate
