### ISSUE TITLE
new version drains battery very quickly

### ISSUE THREAD

**Issue by agodlydeciple** [qklabs/qksms#198] opened 2015-09-03 20:45 UTC
version 2.1.0 has started eating up my battery life.  It has used 25% of my overall battery in the last few hours.  

LG G3 (Verizon) VS985 - Android 5.0.1

**Comment by licaon-kter** [comment] 2015-09-04 04:00
Yep, here too
2.1.0 from F-Droid on CM 12.1

**Comment by LeCoyote** [comment] 2015-09-04 23:02
Confirmed on Lollipop 5.0.2 on an LG G2.
It appears to be linked to another issue where the conversation pane sometimes become blank, regardless of the contact and conversation chosen. It seems to me that when this happens, the app enters some sort of loop that keeps the cpu busy, burning battery and heating up the device a lot. Closing the app makes the problem to away (closing it, not switching tasks).
For testing purposes, I have disabled the quick reply window. I'll post back if I see an improvement.

**Comment by LeCoyote** [comment] 2015-09-05 18:26
After some testing, I could not find any correlation between the empty pane and the coy issue.
I am however able to confirm that the app sometime uses up to 40% of my G2's CPU quite indefinitely, until the app is killed.

**Comment by philherbert** [comment] 2015-09-05 19:28
Also getting this on 4.4.2, LG G2 - battery is draining absurdly quickly, with QKSMS listed as using ~35%. It has the unfortunate consequence of heating up the phone to the point where it turns itself off.

**Comment by joedu12** [comment] 2015-09-06 17:16
Hi, i also have the same issue on my Alcatel OneTouch Idol 3 (TCT 6045Y) on Android 5.0.2.

**Comment by drampelt** [comment] 2015-09-08 19:07
Also having this issue on my Nexus 5

**Comment by l3d00m** [comment] 2015-09-09 15:27
I'm also having this, Android 5.0.2 LG G2. Draining up to 25%

**Comment by Deen-Adam** [comment] 2015-09-10 06:18
Same goes to me on Nexus 6 Android 5.0.2

**Comment by sanguinepar** [comment] 2015-09-14 11:31
Happening to me today (not before for some reason) - in the last 4 hours QKSMS has drained 54% of my battery: http://i.imgur.com/Solv2Ex.png

LGG3, rooted, cloudy 2.2

**Comment by hu475** [comment] 2015-09-23 21:32
Came here to say the same thing. %19 percent battery drain on lollipop 5.1.1

**Comment by ljohn2** [comment] 2015-09-29 03:59
Confirmed here too. Moto X 2014 5.1 
Used 25% of my batter and 4h of cpu at its height. I had to uninstall

**Comment by agodlydeciple** [comment] 2015-09-29 19:11
Bump? 

Has anyone heard any update to this issue?

**Comment by l3d00m** [comment] 2015-09-29 19:19
The dev had recognized the problem and is currently determining what is causing the drain. That's what he said a few days ago on the slack channel.

**Comment by ljohn2** [comment] 2015-09-29 19:46
I got an email reply from the dev

"Hey ****,

Sorry it's taking so long to fix. I wish I could give you an ETA right now but I'm still not able to reproduce the issue on my own phone. I should have some time this week though where hopefully I can debug the issue
Thanks"

**Comment by agodlydeciple** [comment] 2015-09-29 20:00
Thanks for the update!

**Comment by hu475** [comment] 2015-09-30 20:17
I don't know if it helps but it usually happens to me when I click on the Read button as a message arrives and a little screen pops up on the top. After I read the message I move onto another app or just put QKSMS to background and then the problem starts. At least this is my experience so far. Since then I always close QKSMS even if it's on background so no problem so far.

**Comment by l3d00m** [comment] 2015-10-12 18:09
Some things I noticed are: You can stop the drain by force stopping qksms (it's still possible to receive sms) and it will only drain again if you open the qksms main activity.  
Opening qksms only through QK-Reply (ie receiving a sms) doesn't drain battery.  
=> QK-Reply activity isn't causing the drain.

**Comment by moezbhatti** [comment] 2015-10-14 16:21
@l3d00m someone reported to me that it's an MMS wake lock issue, confirmed by a wake lock detector on his rooted phone

**Comment by l3d00m** [comment] 2015-10-14 16:22
Would be great if the cause is finally known!

**Comment by dragontux** [comment] 2015-10-21 08:58
Just stopped by to say this is happening for me too, android 4.4.2.

**Comment by dragontux** [comment] 2015-10-21 09:08
Oh, might be worth mentioning it's the version in f-droid repos, 2.1.0, updated on 2015-09-02. It might have been fixed by the recent pull request, I'll trying building it in a bit and report back

**Comment by l3d00m** [comment] 2015-10-22 15:45
To those of you who are already using v2.2.0 (available through github/gplay beta testers): Are you still experiencing the battery drain?

**Comment by jay1109** [comment] 2015-10-24 03:13
On my phone the issue is still present, but cannot reproduce it.
V2.2.0
Sony xperia z3 compact
Android 5.1.1

**Comment by licaon-kter** [comment] 2015-10-24 07:11
@jay1109 Which one? You either reproduce it so **you have** it or you cannot reproduce it hence **you don't**.

**Comment by jay1109** [comment] 2015-10-24 08:27
Sorry. I do have the issue. It happens sometime, but I do not know,  how to reproduce it. Sometimes it happens after connecting the powersupply, sometimes after pressing the read button from the notification.

**Comment by micdoogs** [comment] 2015-10-26 17:22
This has also been happening to me for about a week now even though I never had this issue with the month long trial app. Today battery usage was up to 37% and leaving my phone inactive doesn't change the rate of the drain.
I'm using an LG G4.

**Comment by micdoogs** [comment] 2015-10-26 17:25
Oh also, the app had been frequently crashing of late as well. This too never happened with the trial app.

**Comment by dylanrb123** [comment] 2015-10-28 15:43
I am having the same issue, first noticed earlier this week (starting 10/23). App version 2.2.1, Android version 5.0, Samsung Galaxy Note 3 on Verizon.

**Comment by agodlydeciple** [comment] 2015-10-28 21:31
Same issue confirmed me as well F-Droid Version 2.2.1 android 5.1.1 LG G3 VS985

**Comment by licaon-kter** [comment] 2015-10-28 23:02
Can't confirm on 5.0.2 or 5.1.1, no drain since 2.2.0 install.

**Comment by joedu12** [comment] 2015-10-28 23:39
Still experiencing the issue with version 2.2.1 on my Alcatel OneTouch Idol 3 (TCT 6045Y) on Android 5.0.2.

**Comment by micdoogs** [comment] 2015-10-29 14:40
The newest update doesn't fix the problem.
I guess I'm going to have to go back to the default texting app until the issue is solved which is unfortunate because I really prefer the QKSMS app but this is honestly a pretty crippling issue.

**Comment by C-Flat** [comment] 2015-11-04 17:43
@moezbhatti Could this be the cause? http://i.imgur.com/7feEHMl.png

**Comment by agodlydeciple** [comment] 2015-11-04 17:59
issue doesn't seem to be present in v2.2.0 of qksms on android 5.1.1. Battery Drain was present in V 2.1.0 and 2.2.1.

**Comment by micdoogs** [comment] 2015-11-04 18:14
I happen to be using the most recent version of QKSMS (updated yesterday) and I'm ruining Android 5.1.1 and the issue is persisting. It's battery usage is at 24% right now which admittedly is an improvement over the 40% it was at when I last posted.
So I think agodlydeciple is mistaken.

**Comment by licaon-kter** [comment] 2015-11-04 18:31
@micdoogs  you are using 2.2.1 aka the latest? s/he said 2.2.0

**Comment by moezbhatti** [comment] 2015-11-04 18:46
@C-Flat oh wow, how did you get that to show? I have been trying to fix something in the TransactionService, but that screenshot looks very suspicious and could definitely be it

**Comment by C-Flat** [comment] 2015-11-04 19:01
I used the method tracer in Android Studio

**Comment by moezbhatti** [comment] 2015-11-04 19:02
@C-Flat did you do anything special to reproduce the issue?

**Comment by C-Flat** [comment] 2015-11-04 19:03
I sent a few pictures messages and used the quick reply beforehand

**Comment by moezbhatti** [comment] 2015-11-04 19:17
Awesome, thanks so much. I can look into this in a couple hours, I'll let you know what I find

**Closed** 2015-11-07 23:03 UTC
