### ISSUE TITLE
Qk-reply shouldn't open if I'm in the qksms app. 

### ISSUE THREAD

**Issue by madboymatt** [qklabs/qksms#179] opened 2015-08-24 19:08 UTC
A lot of times, I'll be in a conversation and then lock my phone, and when I unlock it after receiving a message, the qk-reply is there floating overtop of the same exact conversation in the app. Kind of pointless.

**Comment by l3d00m** [comment] 2015-08-24 19:45
Can repro. This is probably a duplicate of #86 and #91

**Comment by moezbhatti** [comment] 2015-08-26 02:20
Combining with #91

**Closed by moezbhatti** 2015-08-26 02:20 UTC
