### ISSUE TITLE
Weird Transition from conversation to Message list / Inbox

### ISSUE THREAD

**Issue by romelemperado** [qklabs/qksms#529] opened 2016-06-18 19:41 UTC
### DESCRIPTION
I tested on my Android 4.4.3 device and there is a weird transition when you exit(press back button) after reading a message it will show first the phone desktop/home page before going back to your inbox/message list

This is the play store release recently..

### STEPS
1. Open a message then press back button

Check this short video to see it clearly - https://s3.amazonaws.com/uploads.hipchat.com/191793/1367990/zaA37Ol78GsdwXS/VID_20160619_035153.mp4

### EXPECTED
It should go back smoothly to the inbox without showing the desktop screen for few seconds.

### OBSERVATIONS
Transition is okay so for on other devices like Samsung Galaxy S3 and Nexus 6P

**Comment by sm4rk0** [comment] 2016-06-18 21:08
Possible duplicate of #497

**Comment by searchy2** [comment] 2016-06-19 05:08
Tested on Nexus 4 emulator running KitKat. Could not reproduce. What device are you using?

**Comment by romelemperado** [comment] 2016-06-19 06:24
I just tested on 3 Android Kikat Phones

Model:

Myphone my21, my25
Cloud phone 403q

New observation:

This doesn't happen after installing the app from playstore, you need to
completely exit the app or reboot the device then test again.

It is very weird because after installation from playstore the app is
smooth as the previous versions until the app is completely stopped or the
device gets rebooted..
On Jun 19, 2016 1:08 PM, "searchy2" <notifications@github.com> wrote:

Tested on Nexus 4 emulator running KitKat. Could not reproduce. What device
are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/qklabs/qksms/issues/529#issuecomment-226979921>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAgMtZhnYN4oybYd0G6K2jnOjZXFl6HZks5qNM7kgaJpZM4I5BM1>
.

**Comment by moezbhatti** [comment] 2016-06-19 07:00
Let's merge this with #497

**Closed** 2016-06-19 07:00 UTC
