### ISSUE TITLE
Clicking "Read" on the lock screen doesn't clear the pop up box when the screen is unlocked

### ISSUE THREAD

**Issue by samtruong200** [qklabs/qksms#223] opened 2015-10-13 17:32 UTC
Clicking "Read" on the lock screen doesn't clear the pop up box when the screen is unlocked. Instead it clears the message in the box, leaving an empty box. 

Then, when I get a text from someone else, the new box does not show up, it still shows the empty box from the previous, read text. 

I'm using an OnePlus One running Exodus. QKSMS version 2.1.0﻿

**Comment by l3d00m** [comment] 2015-10-13 17:38
duplicate of #91

**Closed** 2015-10-13 17:58 UTC
