### ISSUE TITLE
Random colours for contacts without pictures

### ISSUE THREAD

**Issue by jvoisin** [qklabs/qksms#301] opened 2015-12-07 18:32 UTC
I'm using qksms, but I don't have any picture for my contacts, unlike in this screen:

![contacts]( https://camo.githubusercontent.com/4958b21676fe066bc02b5b66e9874100d334abf0/687474703a2f2f692e696d6775722e636f6d2f7037303633564e2e706e67 )

I only have their first letter in a circle ; it would be great to have a different colour per contact, instead of the same for every one of them.

**Comment by licaon-kter** [comment] 2015-12-07 21:00
Use Micopi to generate an abstract icon ;)

/mark as closed

**Comment by M2ck** [comment] 2015-12-08 12:05
@licaon-kter thanks for the discover Micopi is really great!
However IMO it should be nice to have a random color feature for conctats without picture like available default on Google Messanger for example.

**Comment by licaon-kter** [comment] 2015-12-08 12:08
Yeah, I know. :)

**Comment by xavihernandez** [comment] 2016-01-07 13:39
duplicate of #133

**Closed** 2016-01-07 15:47 UTC
