### ISSUE TITLE
[BUG] Not possible to select message with a URL or phone number 

### ISSUE THREAD

**Issue by Alexandrejoe** [qklabs/qksms#448] opened 2016-03-18 15:25 UTC
### DESCRIPTION
I'm not able to select with long press an SMS with a URL link or a phone number inside.

### STEPS
- Check a SMS with a link or phone number in the content.
- Example: SMS Content = "Check this https://www.reddit.com/r/QKSMS/".
- Pressing the message open the link (OK).
- Long press on the message doesn't have any effect (KO).

### EXPECTED
A long press on the message should open the classic "Message option" menu.

### OBSERVATIONS
A long press on a message with a link or phone number in content doesn't have any effect.

(sorry if duplicated or not a bug, I'm new here)

**Comment by moezbhatti** [comment] 2016-04-04 00:53
Duplicate of #171

**Closed** 2016-04-04 00:53 UTC
Labels: duplicate
