### ISSUE TITLE
Enhancement Request: Random color scheme for each conversation at startup

### ISSUE THREAD

**Issue by valerio-bozzolan** [qklabs/qksms#318] opened 2015-12-22 21:38 UTC
Don't be cruel with this request. You are talking with my girlfriend  :unamused:

Anyway... thanks for this great Free as in Freedom software!

**Comment by licaon-kter** [comment] 2015-12-22 21:42
Duplicate of https://github.com/qklabs/qksms/issues/301

**Comment by valerio-bozzolan** [comment] 2015-12-22 22:10
@licaon-kter Sorry no... I'm talking of the screen, not the avatar.

**Comment by licaon-kter** [comment] 2015-12-22 22:11
my bad.

**Comment by moezbhatti** [comment] 2015-12-24 23:46
Do you want them random, or user-selectable?

**Comment by valerio-bozzolan** [comment] 2015-12-24 23:52
(Let me ask to my dear:)

«RANDOM!!!!!!!»

I think random :) Thanks so much.

**Comment by szabolcsx** [comment] 2015-12-26 19:58
The combination of them would be better I guess: each time when a new conversation is started it gets a random color and the user could change that if it doesn't like.

**Comment by valerio-bozzolan** [comment] 2015-12-26 20:09
+1 for @szabolcsx

**Comment by xavihernandez** [comment] 2016-01-07 13:38
duplicate of #133

**Closed** 2016-01-07 15:47 UTC
