### ISSUE TITLE
When writing a  new text, if switched to landscape, text is no longer here 

### ISSUE THREAD

**Issue by burkben1** [qklabs/qksms#88] opened 2015-07-30 20:32 UTC
Using version 1.11.3 on HTC ONE M8 with android 5.01 

Strange bug, if I begin a text and switch  to landscape mode ( from horizontal mode ) the text will  be saved as a draft . If saved as a draft, the draft won't appear and so  won't be useful.

**Comment by moezbhatti** [comment] 2015-08-16 05:19
Is this issue still appearing in 1.12+?

**Comment by burkben1** [comment] 2015-08-16 10:51
Yeah it does, but I discovered that the draft ends in the stock sms app 

But still no explanations to why the switch to landscape saves it to draft...

**Comment by l3d00m** [comment] 2015-08-18 09:33
Cannot reproduce using v2.0.1 and android 5.0.2 (LG G2). Text just gets saved as draft, but it's still there.

Is QKSMS your default SMS app?

**Comment by burkben1** [comment] 2015-08-18 09:44
Yes it is 
Unfortunately I don't have any friends with the same phone as me :( 
I think it's an issue with the stock app interfering with qksms..

**Comment by therob84** [comment] 2016-02-07 14:02
I can confirm this bug happened at least once with version 2.5.2 at my Fairphone2 | Android 5.1 with qksms as default app.

Unfortunately I could not reproduce this after trying it now.

Maybe it could be connected to this: 
I also encountered the same problem (text is not saved as draft, it vanished) when I received an SMS and clicked the notification to read while typing an text....it just dissapeared.
Now I could not reproduces this, but it happened for sure 2 times before...

**Comment by moezbhatti** [comment] 2016-02-28 21:13
Fixed with #314

**Closed by moezbhatti** 2016-02-28 21:13 UTC

**Comment by therob84** [comment] 2016-03-01 13:38
I can confirm that the rotation problem seems to be fixed for v2.5.3.

**Comment by therob84** [comment] 2016-03-14 08:09
Unfortunately I have to come back to this bug:
**What works:** the text is saved now correctly, when screen is turned.
**What does not work:** the list of recipients is emptied after turning the screen.
I don't know if you included this bug with latest changes or if it was unnoticed there before....

**Comment by moezbhatti** [comment] 2016-03-16 05:26
@therob84 can you open a new issue for that?

**Comment by billic** [comment] 2016-03-16 08:13
@moezbhatti I can. see #443

**Comment by moezbhatti** [comment] 2016-03-16 08:13
Perfect, thanks
