### ISSUE TITLE
 The input text disappears upon rotation

### ISSUE THREAD

**Issue by elbooster** [qklabs/qksms#353] opened 2016-01-14 18:04 UTC
If I write a long text and unfortunately the toggle screen (rotation) all the entered text disappears.

QKSMS V2.5.1
On Honor 7
Android 5.0.2

**Comment by moezbhatti** [comment] 2016-01-20 03:39
Is this inside a conversation or the compose screen?

**Comment by fredcooke** [comment] 2016-01-20 04:55
This is a duplicate of an eariler bug that I wrote or have comments on. Not sure of the number and couldn't find it looking just now. Would love to see this fixed, the recipient also disappears if it's a new message.

**Comment by elbooster** [comment] 2016-01-20 05:51
It is in the composition screen and conversation.
The recipient effectively disappears as if it is a new message.

**Comment by moezbhatti** [comment] 2016-02-28 21:32
Fixed as of https://github.com/qklabs/qksms/commit/c37088ab2e6b71f775b73e15e4941a20c45b4c5f

**Closed by moezbhatti** 2016-02-28 21:33 UTC
Labels: bug
