### ISSUE TITLE
App crashes on first run

### ISSUE THREAD

**Issue by Winkelried** [qklabs/qksms#217] opened 2015-09-27 15:43 UTC
Hello

I use an Alcatel OneTouch Idol 2 Mini L with Android 4.3 and QKSMS 2.10.

On the first launch of the app, the one with the small introduction about colors and night mode, when I try to:

Use the return key;
Use the menu key;
Press the terminate area;

The app crashes. I can use the home key but the app will crash when I launch it again. The only way to use it is to add the widget then to launch the app with.

**Comment by smarquespt** [comment] 2015-10-10 14:26
This also happens to me in f-droid release.

**Comment by rick9791** [comment] 2015-10-16 09:08
Same thing over here, I'm on Android 4.2.2, using the F-Droid release.

**Comment by moezbhatti** [comment] 2015-10-22 02:37
Works fine for me. Are you able to get a stack trace?

**Comment by smarquespt** [comment] 2015-10-22 08:38
@moezbhatti 
I can try to get one. Can you tell me how to do it?

**Comment by smarquespt** [comment] 2015-10-23 08:52
I´ve managed to narrow down this issue, because (form) it only happens at a fresh install of 2.1 release.

What I´ve tried:

1 -  Uninstall QK 2.1, install it from f-droid or google play.

Result: Crash

2 - Uninstall 2.1, install 2.01 (f-droid) and run the wizard. Now install 2.1 (f-droid), start app.

Result: It runs just as before.

So what I could found out is that is somewhat related to fresh installs and only in 2.1 release, because if 2.1 is updating previous release it works just fine.

**Comment by moezbhatti** [comment] 2015-10-23 16:42
Is the crash still happening with 2.2?

**Comment by rick9791** [comment] 2015-10-23 21:10
No, not happening anymore to me

**Comment by shsuenishi** [comment] 2015-10-23 22:34
Neither 2.10 nor 2.20 will install clean on Android 4.1.2. If you install 2.20 over 2.01 then the app works as expected otherwise it will crash after selecting a color and tapping 'Finish'.

**Comment by smarquespt** [comment] 2015-10-24 09:18
I can confirm what @shsuenishi said. It happens same thing with me.

**Comment by smarquespt** [comment] 2015-10-25 19:46
Don´t know if this log is useful because I´m not a developer but here it is:

build.board: Y530-U00
build.bootloader: unknown
build.brand: Huawei
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: hwY530-U00
build.display: Y530-U00V100R001C900B189
build.fingerprint: Huawei/Y530-U00/hwY530-U00:4.3/HuaweiY530-U00/C900B189:user/ota-rel-keys,release-keys
build.hardware: qcom
build.host: huawei-desktop
build.id: HuaweiY530-U00
build.manufacturer: HUAWEI
build.model: HUAWEI Y530-U00
build.product: Y530-U00
build.radio: unknown
build.serial: 88e3abce72db
build.tags: release-keys
build.time: 1397296389000
build.type: user
build.user: huawei
version.codename: REL
version.incremental: C900B189
version.release: 4.3
version.sdk_int: 18

10-25 00:43:43.659 I/ActivityManager(964): Start proc com.moez.QKSMS for activity com.moez.QKSMS/.ui.MainActivity-Teal: pid=6220 uid=10099 gids={50099, 3003, 1028, 1015}
10-25 00:44:27.479 I/ActivityManager(964): Process com.moez.QKSMS (pid 6220) has died.
10-25 00:45:10.619 I/ActivityManager(964): Start proc com.moez.QKSMS for broadcast com.moez.QKSMS/.receiver.IconColorReceiver: pid=7571 uid=10099 gids={50099, 3003, 1028, 1015}
10-25 00:47:19.930 I/ActivityManager(964): No longer want com.moez.QKSMS (pid 7571): empty #11
10-25 01:59:55.661 I/ActivityManager(964): Force stopping package com.moez.QKSMS appid=10099 user=-1
10-25 01:59:55.721 W/PackageManager(964): Couldn't delete native library directory /data/app-lib/com.moez.QKSMS
10-25 01:59:56.101 I/ActivityManager(964): Force stopping package com.moez.QKSMS appid=10099 user=0
10-25 01:59:56.761 I/AlarmManager(964): Remove com.moez.QKSMS from mIntentHisRW
10-25 01:59:58.361 D/BackupManagerService(964): Received broadcast Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.moez.QKSMS flg=0x8000010 (has extras) }
10-25 01:00:40.961 W/ActivityManager(964): No content provider found for permission revoke: file:///data/data/com.android.vending/cache/copies/com.moez.QKSMS-598149503.apk
10-25 01:00:41.151 W/ActivityManager(964): No content provider found for permission revoke: file:///data/data/com.android.vending/cache/copies/com.moez.QKSMS-598149503.apk
10-25 01:00:46.781 I/ActivityManager(964): Force stopping package com.moez.QKSMS appid=10123 user=-1
10-25 01:00:47.041 W/PackageManager(964): Not granting permission android.permission.CHANGE_CONFIGURATION to package com.moez.QKSMS (protectionLevel=50 flags=0x18be44)
10-25 01:00:47.041 W/PackageManager(964): Unknown permission com.sec.android.provider.badge.permission.READ in package com.moez.QKSMS
10-25 01:00:47.041 W/PackageManager(964): Unknown permission com.sec.android.provider.badge.permission.WRITE in package com.moez.QKSMS
10-25 01:00:47.041 W/PackageManager(964): Unknown permission com.htc.launcher.permission.READ_SETTINGS in package com.moez.QKSMS
10-25 01:00:47.041 W/PackageManager(964): Unknown permission com.htc.launcher.permission.UPDATE_SHORTCUT in package com.moez.QKSMS
10-25 01:00:47.041 W/PackageManager(964): Unknown permission com.sonyericsson.home.permission.BROADCAST_BADGE in package com.moez.QKSMS
10-25 01:00:47.041 W/PackageManager(964): Unknown permission com.anddoes.launcher.permission.UPDATE_COUNT in package com.moez.QKSMS
10-25 01:00:47.041 W/PackageManager(964): Unknown permission com.majeur.launcher.permission.UPDATE_BADGE in package com.moez.QKSMS
10-25 01:00:50.511 D/BackupManagerService(964): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.moez.QKSMS flg=0x8000010 (has extras) }
10-25 01:00:53.991 I/ActivityManager(964): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.moez.QKSMS cmp=com.moez.QKSMS/.ui.MainActivity-Teal} from pid 24601
10-25 01:00:54.101 I/ActivityManager(964): Start proc com.moez.QKSMS for activity com.moez.QKSMS/.ui.MainActivity-Teal: pid=26897 uid=10123 gids={50123, 3003, 1028, 1015}
10-25 01:00:57.641 I/ActivityManager(964): START u0 {cmp=com.moez.QKSMS/.ui.welcome.WelcomeActivity} from pid 26897
10-25 01:00:58.201 W/ActivityManager(964): Activity pause timeout for ActivityRecord{41b5e8d0 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:01:05.891 I/ActivityManager(964): Process com.moez.QKSMS (pid 26897) has died.
10-25 01:01:05.891 I/WindowState(964): WIN DEATH: Window{41c8ec70 u0 com.moez.QKSMS/com.moez.QKSMS.ui.welcome.WelcomeActivity}
10-25 01:01:05.981 W/ActivityManager(964): Force removing ActivityRecord{42487220 u0 com.moez.QKSMS/.ui.welcome.WelcomeActivity}: app died, no saved state
10-25 01:01:05.991 I/ActivityManager(964): Start proc com.moez.QKSMS for activity com.moez.QKSMS/.ui.MainActivity-Teal: pid=27230 uid=10123 gids={50123, 3003, 1028, 1015}
10-25 01:01:07.221 I/ActivityManager(964): START u0 {cmp=com.moez.QKSMS/.ui.welcome.WelcomeActivity} from pid 27230
10-25 01:01:07.721 W/ActivityManager(964): Activity pause timeout for ActivityRecord{41b5e8d0 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:01:09.211 E/AndroidRuntime(27230): 	at com.moez.QKSMS.ui.dialog.DefaultSmsHelper.<init>(DefaultSmsHelper.java:37)
10-25 01:01:09.211 E/AndroidRuntime(27230): 	at com.moez.QKSMS.ui.MainActivity.onActivityResult(MainActivity.java:338)
10-25 01:01:09.241 W/ActivityManager(964):   Force finishing activity com.moez.QKSMS/.ui.welcome.WelcomeActivity
10-25 01:01:09.251 W/ActivityManager(964):   Force finishing activity com.moez.QKSMS/.ui.MainActivity-Teal
10-25 01:01:09.751 W/ActivityManager(964): Activity pause timeout for ActivityRecord{419102f8 u0 com.moez.QKSMS/.ui.welcome.WelcomeActivity}
10-25 01:01:12.361 I/ActivityManager(964): Process com.moez.QKSMS (pid 27230) has died.
10-25 01:01:12.361 W/ActivityManager(964): Scheduling restart of crashed service com.moez.QKSMS/com.android.mms.transaction.TransactionService in 11520ms
10-25 01:01:12.361 I/WindowState(964): WIN DEATH: Window{41cef1c0 u0 com.moez.QKSMS/com.moez.QKSMS.ui.MainActivity-Teal}
10-25 01:01:23.901 I/ActivityManager(964): Start proc com.moez.QKSMS for service com.moez.QKSMS/com.android.mms.transaction.TransactionService: pid=27443 uid=10123 gids={50123, 3003, 1028, 1015}
10-25 01:01:25.111 E/Utils   (27443): 	at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
10-25 01:01:25.151 E/Utils   (27443): 	at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
10-25 01:01:25.171 E/Utils   (27443): 	at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
10-25 01:01:25.201 E/Utils   (27443): 	at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
10-25 01:01:36.381 I/ActivityManager(964): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.moez.QKSMS/.ui.MainActivity-Teal} from pid 26231
10-25 01:01:36.521 I/dalvikvm(27443): Could not find method android.os.PowerManager.isInteractive, referenced from method com.moez.QKSMS.ui.base.QKActivity.isScreenOn
10-25 01:01:36.581 I/ActivityManager(964): START u0 {cmp=com.moez.QKSMS/.ui.welcome.WelcomeActivity} from pid 27443
10-25 01:01:36.691 I/dalvikvm(27443): Could not find method android.telephony.TelephonyManager.getMmsUAProfUrl, referenced from method com.moez.QKSMS.ui.dialog.mms.MMSSetupFragment.getSupportEmailBody
10-25 01:01:37.081 W/ActivityManager(964): Activity pause timeout for ActivityRecord{41c03fb8 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:01:37.741 I/ActivityManager(964): Displayed info r = ActivityRecord{41c03fb8 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:01:37.751 I/ActivityManager(964): Displayed com.moez.QKSMS/.ui.welcome.WelcomeActivity: +672ms (total +1s272ms)
10-25 01:01:40.891 I/dalvikvm(27443): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method com.moez.QKSMS.ui.dialog.DefaultSmsHelper.<init>
10-25 01:01:42.451 E/AndroidRuntime(27443): 	at com.moez.QKSMS.ui.dialog.DefaultSmsHelper.<init>(DefaultSmsHelper.java:37)
10-25 01:01:42.451 E/AndroidRuntime(27443): 	at com.moez.QKSMS.ui.MainActivity.onActivityResult(MainActivity.java:338)
10-25 01:01:42.501 W/ActivityManager(964):   Force finishing activity com.moez.QKSMS/.ui.MainActivity-Teal
10-25 01:01:43.001 W/ActivityManager(964): Activity pause timeout for ActivityRecord{41c03fb8 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:01:45.721 I/ActivityManager(964): Process com.moez.QKSMS (pid 27443) has died.
10-25 01:01:45.721 I/WindowState(964): WIN DEATH: Window{4203f528 u0 com.moez.QKSMS/com.moez.QKSMS.ui.welcome.WelcomeActivity}
10-25 01:02:46.201 I/ActivityManager(964): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.moez.QKSMS/.ui.MainActivity-Teal} from pid 26231
10-25 01:02:46.271 I/ActivityManager(964): Start proc com.moez.QKSMS for activity com.moez.QKSMS/.ui.MainActivity-Teal: pid=29346 uid=10123 gids={50123, 3003, 1028, 1015}
10-25 01:02:46.781 I/dalvikvm(29346): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method com.moez.QKSMS.MmsConfig.isSmsEnabled
10-25 01:02:46.841 I/dalvikvm(29346): Could not find method android.os.PowerManager.isInteractive, referenced from method com.moez.QKSMS.ui.base.QKActivity.isScreenOn
10-25 01:02:46.861 I/ActivityManager(964): START u0 {cmp=com.moez.QKSMS/.ui.welcome.WelcomeActivity} from pid 29346
10-25 01:02:46.981 I/dalvikvm(29346): Could not find method android.telephony.TelephonyManager.getMmsUAProfUrl, referenced from method com.moez.QKSMS.ui.dialog.mms.MMSSetupFragment.getSupportEmailBody
10-25 01:02:47.361 W/ActivityManager(964): Activity pause timeout for ActivityRecord{418ddf10 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:02:47.721 I/dalvikvm(29346): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method com.moez.QKSMS.mmssms.Utils.isDefaultSmsApp
10-25 01:02:47.741 E/Utils   (29346): 	at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
10-25 01:02:48.031 E/Utils   (29346): 	at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
10-25 01:02:48.171 I/ActivityManager(964): Displayed info r = ActivityRecord{418ddf10 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:02:48.181 I/ActivityManager(964): Displayed com.moez.QKSMS/.ui.welcome.WelcomeActivity: +818ms (total +1s926ms)
10-25 01:02:51.481 V/WidgetProvider(29346): onReceive intent: Intent { act=com.moez.QKSMS.intent.action.ACTION_NOTIFY_DATASET_CHANGED flg=0x10 cmp=com.moez.QKSMS/.ui.widget.WidgetProvider }
10-25 01:02:52.201 I/dalvikvm(29346): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method com.moez.QKSMS.ui.dialog.DefaultSmsHelper.<init>
10-25 01:02:53.491 E/AndroidRuntime(29346): 	at com.moez.QKSMS.ui.dialog.DefaultSmsHelper.<init>(DefaultSmsHelper.java:37)
10-25 01:02:53.491 E/AndroidRuntime(29346): 	at com.moez.QKSMS.ui.MainActivity.onActivityResult(MainActivity.java:338)
10-25 01:02:53.491 W/ActivityManager(964):   Force finishing activity com.moez.QKSMS/.ui.MainActivity-Teal
10-25 01:02:53.991 W/ActivityManager(964): Activity pause timeout for ActivityRecord{418ddf10 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:02:56.681 I/ActivityManager(964): Process com.moez.QKSMS (pid 29346) has died.
10-25 01:02:56.681 I/WindowState(964): WIN DEATH: Window{41e31ca8 u0 com.moez.QKSMS/com.moez.QKSMS.ui.welcome.WelcomeActivity}
10-25 01:04:05.901 I/ActivityManager(964): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.moez.QKSMS/.ui.MainActivity-Teal} from pid 26231
10-25 01:04:05.981 I/ActivityManager(964): Start proc com.moez.QKSMS for activity com.moez.QKSMS/.ui.MainActivity-Teal: pid=31587 uid=10123 gids={50123, 3003, 1028, 1015}
10-25 01:04:06.181 I/dalvikvm(31587): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method com.moez.QKSMS.MmsConfig.isSmsEnabled
10-25 01:04:06.231 I/dalvikvm(31587): Could not find method android.os.PowerManager.isInteractive, referenced from method com.moez.QKSMS.ui.base.QKActivity.isScreenOn
10-25 01:04:06.261 I/ActivityManager(964): START u0 {cmp=com.moez.QKSMS/.ui.welcome.WelcomeActivity} from pid 31587
10-25 01:04:06.381 I/dalvikvm(31587): Could not find method android.telephony.TelephonyManager.getMmsUAProfUrl, referenced from method com.moez.QKSMS.ui.dialog.mms.MMSSetupFragment.getSupportEmailBody
10-25 01:04:06.781 W/ActivityManager(964): Activity pause timeout for ActivityRecord{41c5ee58 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:04:06.981 I/dalvikvm(31587): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method com.moez.QKSMS.mmssms.Utils.isDefaultSmsApp
10-25 01:04:06.991 E/Utils   (31587): 	at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
10-25 01:04:07.251 E/Utils   (31587): 	at com.moez.QKSMS.mmssms.Utils.setMobileDataEnabled(Utils.java:250)
10-25 01:04:07.401 I/ActivityManager(964): Displayed info r = ActivityRecord{41c5ee58 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:04:07.411 I/ActivityManager(964): Displayed com.moez.QKSMS/.ui.welcome.WelcomeActivity: +634ms (total +1s440ms)
10-25 01:04:10.151 I/dalvikvm(31587): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method com.moez.QKSMS.ui.dialog.DefaultSmsHelper.<init>
10-25 01:04:11.491 E/AndroidRuntime(31587): 	at com.moez.QKSMS.ui.dialog.DefaultSmsHelper.<init>(DefaultSmsHelper.java:37)
10-25 01:04:11.491 E/AndroidRuntime(31587): 	at com.moez.QKSMS.ui.MainActivity.onActivityResult(MainActivity.java:338)
10-25 01:04:11.501 W/ActivityManager(964):   Force finishing activity com.moez.QKSMS/.ui.MainActivity-Teal
10-25 01:04:12.001 W/ActivityManager(964): Activity pause timeout for ActivityRecord{41c5ee58 u0 com.moez.QKSMS/.ui.MainActivity-Teal}
10-25 01:04:12.671 I/ActivityManager(964): Process com.moez.QKSMS (pid 31587) has died.
10-25 01:04:12.671 I/WindowState(964): WIN DEATH: Window{41ca1130 u0 com.moez.QKSMS/com.moez.QKSMS.ui.welcome.WelcomeActivity}

**Comment by moezbhatti** [comment] 2015-10-26 00:29
Figured out the issue, it'll be fixed in the next update

**Comment by moezbhatti** [comment] 2015-10-26 00:30
Actually it's fixed in https://github.com/qklabs/qksms/commit/5845e694ea32350a9197163ddef778f063a981a7

**Closed by moezbhatti** 2015-10-26 00:30 UTC
Labels: bug, needs-repro
