### ISSUE TITLE
[Request] Show name under messages in group texts

### ISSUE THREAD

**Issue by W1nks** [qklabs/qksms#445] opened 2016-03-17 14:31 UTC
Hi,

I've noticed that in group texts it doesn't show the name of the person who sent the message most of the time (it seems like it's normally just the last message received).  If I click on the message to view more details it will show the number of who it is from but not their name.  Sometimes under the message it will show the time it was received and the contact who sent it (again, I think it's just the last received message).  Would it be possible to make this show up for all messages in group texts?  Sometimes I will receive multiple messages so I wont know who sent what. 

Thank you and keep up the good word!  This is by far my favorite messaging app I've ever used!

**Comment by moezbhatti** [comment] 2016-03-17 16:07
I actually fixed this last night! I'll be releasing it this weekend

**Comment by moezbhatti** [comment] 2016-03-17 16:07
Marking as duplicate of #116

**Closed by moezbhatti** 2016-03-17 16:07 UTC
Labels: duplicate
